name: Compilar y Subir App.exe

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Clonar el código local
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar librerías y PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Compilar a .exe
      run: |
        # Usamos --windowed para ocultar la consola
        # El archivo de salida se llamará "App.exe"
        pyinstaller --noconfirm --onefile --windowed --name "App" APP.py

    - name: Subir archivo a Ejecutables
      env:
        GH_TOKEN: ${{ secrets.TOKEN_EJECUTABLES }}
      run: |
        # Sube el ejecutable al repositorio central de Ejecutables en el tag 'produccion'
        gh release upload Produccion dist/App.exe --repo idwin1/Ejecutables --clobber
